### PR TITLE
Gh 862 migrate ci

### LINKED ISSUE #862: Migrate CI and releases to Github actions
Using Gaffer github actions as a guide migrate CI and Release procedure from Travis CI.org to Github actions

### PR DESCRIPTION
**Pull request by d47853**
# Related Issue

- Resolve #862

### CODE REVIEW

**Comment by d47853** [comment]
Closing while hanging UI tests are looked into

**Comment by t92549** [comment]
Reopening, hoping to fix UI tests and get CI process moved to GitHub Actions as travis-ci.org has stopped building

**Comment by t92549** [comment]
I think this is all working now, will confer with @d47853. Would also close #907

**Review by t92549 — APPROVED** [review]
@d47853 Approves of my tinkering to what was originally his PR

**Pull request merged**
