### PR TITLE
Gh 863 ssl proxies

### PR DESCRIPTION
**Pull request by t92549**

### CODE REVIEW

**Comment by t92549** [comment]
Before this is merged some more work is needed on deserialising the responses from gaffer as they are not always json.

**Comment by t92549** [comment]
Ready for review, closes #863

**Comment by t92549** [comment]
todo: Remove f-strings

**Review by sw96411 — CHANGES_REQUESTED** [review]
To follow-up on our in-person chat Friday...

This looks great and seems to work in testing in a realistic environment.  Only feedback I would give is to make sure requests 1.24.0 is specified in the requirements.txt file.  1.25.0 has issues with https proxies IIRC

**Review by p3430233 — APPROVED** [review]

**Pull request merged**
