### PR TITLE
Gh 627 tables difficult to scroll

### PR DESCRIPTION
**Pull request by n288TJYRX**
#627

### CODE REVIEW

**Comment by n288TJYRX** [comment]
I've managed to get rid of the second scrollbar without changing the flex. Just need a review.

**Comment by d47853** [comment]
Problem here is that clicking and dragging could be used for trying to highlight text but now moves the table which is bad for user experience in the event a user is trying to copy a seed for input into a follow on operation. It should scroll when the users mouse moves close to the left and right. Alternatively you could find a way of always showing a scroll bar permanently

**Comment by n288TJYRX** [comment]
Done, but do you want me to write some unit tests aswell?

**Comment by d47853** [comment]
If you can, that would be great

**Comment by n288TJYRX** [comment]
Okay I had a go at writing unit tests for this but struggled. I'm not sure how to test the html elements without mocking them, they should be created but when I do getElementById() I just get null. To mock them I would have to just copy all of the code that adds the event listeners into the tests aswell and the code that controls the scroll behaviour. That doesn't seem like a nice way to test it to me. Any suggestions? Otherwise I'll leave this for now and let someone else have a go.

**Pull request closed without merging**
