### PR TITLE
Gh 634 Removed 2 instances of 'md-select-on-focus" from dynamic-input.html

### LINKED ISSUE #634: Remove md-select-on-focus property from parameters
The property causes parameters and configuration to be auto-selected. This is annoying for users who want to make minor changes to properties as they have to click multiple times or risk overwriting the property entirely.

Remove the property from the dynamic input template to resolve the issue.

### PR DESCRIPTION
**Pull request by g609bmsma**
Fixes #634

### CODE REVIEW

**Comment by g609bmsma** [comment]
very confused as to why this pull request is failing - on my machine it passes checkstyle, Panalyze and a clean install, but upon passing to Travis, there is a failure in the ui portion. Seems to be an issue with phantomjs binary - any solution to this, other than possibly making a fresh fork and starting the branch anew?

**Comment by d47853** [comment]
I believe it's because of the QueryBuilderST. One of the tests creates a parameterised operation. It clicks the parameter input (default value is 1). Because of the removal of the md-select-on-focus property, the input is no longer highlighted and is instead appended to. Therefore typing "2" now makes the input 12 rather than 2. 

To fix this, update the QueryBuilderST to enter a backspace key before 2.

**Comment by d47853** [comment]
That's why we get this in the test output:
It's expecting the output to be limited to two elements, but twelve are in the results

Failed tests: 
  QueryBuilderST.shouldBeAbleToRunParameterisedQueries:259 expected:<[{class=uk.gov.gchq.gaffer.operation.data.EntitySeed, vertex=352952,178032}, {class=uk.gov.gchq.gaffer.operation.data.EntitySeed, vertex=M5:18A}]> but was:<[{class=uk.gov.gchq.gaffer.operation.data.EntitySeed, vertex=352952,178032}, {class=uk.gov.gchq.gaffer.operation.data.EntitySeed, vertex=M5:18A}, {class=uk.gov.gchq.gaffer.operation.data.EntitySeed, vertex=M5:18A}, {class=uk.gov.gchq.gaffer.operation.data.EntitySeed, vertex=M5:18A}, {class=uk.gov.gchq.gaffer.operation.data.EntitySeed, vertex=M5:18A}, {class=uk.gov.gchq.gaffer.operation.data.EntitySeed, vertex=M5:18A}, {class=uk.gov.gchq.gaffer.operation.data.EntitySeed, vertex=M5:18A}, {class=uk.gov.gchq.gaffer.operation.data.EntitySeed, vertex=M5:18A}, {class=uk.gov.gchq.gaffer.operation.data.EntitySeed, vertex=M5:18A}, {class=uk.gov.gchq.gaffer.operation.data.EntitySeed, vertex=M5:18A}, {class=uk.gov.gchq.gaffer.operation.data.EntitySeed, vertex=M5:18A}, {class=uk.gov.gchq.gaffer.operation.data.EntitySeed, vertex=M5:18A}]>

**Comment by g609bmsma** [comment]
> I believe it's because of the QueryBuilderST. One of the tests creates a parameterised operation. It clicks the parameter input (default value is 1). Because of the removal of the md-select-on-focus property, the input is no longer highlighted and is instead appended to. Therefore typing "2" now makes the input 12 rather than 2.
> 
> To fix this, update the QueryBuilderST to enter a backspace key before 2.

Ah ok, I'll get on that now, thanks

**Comment by g609bmsma** [comment]
Finally managed to get it working after inspecting the selenium docs and realising it need an underscore

**Comment by d47853** [comment]
Nice one. I'll merge this after I have released gaffer tools 1.8.1.

**Pull request merged**
